name: Deploy Spring Boot application

# This triggers the Pipeline
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    # Get a new instance of a computer / virtual machine
    runs-on: ubuntu-latest
    steps:
        # Every step should typically have `name` but MUST have either a `uses` or `with`
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build and run tests for Spring Boot Application
      - name: Build Spring Boot project with Maven
        run: mvn -B package --file pom.xml

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action plugin written for Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bug-wars-game-engine"
          heroku_email: "jerry.codecamp@gmail.com"
          justlogin: true

      - name: Deploy to Heroku using Heroku CLI
        run: |
          heroku plugins:install java
          heroku buildpacks:clear --app bug-wars-game-engine
          heroku deploy:jar target/bug-wars-game-engine-0.0.1-SNAPSHOT.jar --app bug-wars-game-engine
